platform :ios, '7.0'
pod 'RNCryptor',       '~> 2.1'
pod 'FMDB', '~> 2.1'
pod 'SBJson', '~> 3.2'
pod 'HockeySDK', '~> 3.0.0'
pod 'libPhoneNumber-iOS', '~> 0.5.7.1'
pod 'AFNetworking', '~> 2.0.1'
pod 'PonyDebugger', '~> 0.3.0'
pod 'SQLCipher', '~> 2.1.1'