CREATE TABLE drafts (_id INTEGER PRIMARY KEY, thread_id INTEGER, type TEXT, value TEXT);
CREATE INDEX IF NOT EXISTS draft_thread_index ON drafts (thread_id);
CREATE TABLE identities (_id INTEGER PRIMARY KEY, key TEXT UNIQUE, name TEXT UNIQUE, mac TEXT);
CREATE TABLE mms (_id INTEGER PRIMARY KEY, thread_id INTEGER, date INTEGER, date_received INTEGER, msg_box INTEGER, read INTEGER DEFAULT 0, m_id TEXT, sub TEXT, sub_cs INTEGER, ct_t TEXT, ct_l TEXT, exp INTEGER, m_cls TEXT, m_type INTEGER, v INTEGER, m_size INTEGER, pri INTEGER, rr INTEGER, rpt_a INTEGER, resp_st INTEGER, st INTEGER, tr_id TEXT, retr_st INTEGER, retr_txt TEXT, retr_txt_cs INTEGER, read_status INTEGER, ct_cls INTEGER, resp_txt TEXT, d_tm INTEGER, d_rpt INTEGER);
CREATE INDEX IF NOT EXISTS mms_thread_id_index ON mms (thread_id);
CREATE INDEX IF NOT EXISTS mms_read_index ON mms (read);
CREATE INDEX IF NOT EXISTS mms_read_and_thread_id_index ON mms(read,thread_id);
CREATE INDEX IF NOT EXISTS mms_message_box_index ON mms (msg_box);
CREATE TABLE part (_id INTEGER PRIMARY KEY, mid INTEGER, seq INTEGER DEFAULT 0, ct TEXT, name TEXT, chset INTEGER, cd TEXT, fn TEXT, cid TEXT, cl TEXT, ctt_s INTEGER, ctt_t TEXT, encrypted INTEGER, _data TEXT);
CREATE INDEX IF NOT EXISTS part_mms_id_index ON part (mid);
CREATE TABLE sms (_id integer PRIMARY KEY, thread_id INTEGER, address TEXT, person INTEGER, date INTEGER, date_sent INTEGER, protocol INTEGER, read INTEGER DEFAULT 0, status INTEGER DEFAULT -1,type INTEGER, reply_path_present INTEGER, subject TEXT, body TEXT, service_center TEXT);
CREATE INDEX IF NOT EXISTS sms_thread_id_index ON sms (thread_id);
CREATE INDEX IF NOT EXISTS sms_read_index ON sms (read);
CREATE INDEX IF NOT EXISTS sms_read_and_thread_id_index ON sms(read,thread_id);
CREATE INDEX IF NOT EXISTS sms_type_index ON sms (type);
CREATE TABLE thread (_id INTEGER PRIMARY KEY, date INTEGER DEFAULT 0, message_count INTEGER DEFAULT 0, recipient_ids TEXT, snippet TEXT, snippet_cs INTEGER DEFAULT 0, read INTEGER DEFAULT 1, type INTEGER DEFAULT 0, error INTEGER DEFAULT 0, has_attachment INTEGER DEFAULT 0);
CREATE INDEX IF NOT EXISTS thread_recipient_ids_index ON thread (recipient_ids);
CREATE TABLE mms_addresses (_id INTEGER PRIMARY KEY, mms_id INTEGER, type INTEGER, address TEXT, address_charset INTEGER);
CREATE INDEX IF NOT EXISTS mms_addresses_mms_id_index ON mms_addresses (mms_id);